config/routes.rb
Rails.application.routes.draw do
  root 'groups#index'
  get 'index', to: 'static_pages#index'
  get 'static_pages/logout', to: 'static_pages#logout'
  resources :groups, except: [:destroy]
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
  }
  # get 'users/show'
  # root 'static_pages#index'
  # get 'static_pages/logout', to: 'static_pages#logout'
  # devise_for :users, :controllers => {
  #   :registrations => 'users/registrations'
  # }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  
  validates :name, presence: true
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable
  
  has_many :group_users
  has_many :groups, through: :group_users
  
  validates :name, presence: true, length: { minimum: 1, maximum: 20 }
  validates :email, presence: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :login_required

  # def login_required
  #   if already_logged_in?
  #     redirect_to signin_path
  #   end
  # end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # before_action :ensure_correct_user
  
  def index
    if !user_signed_in?
      redirect_to index_path
    end
    # @groups = Group.all
  end
  
  def show
    @group = Group.find(params[:id])
  end
  
  def new
    @group = Group.new
  end
  
  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id
    if @group.save
      redirect_to groups_path
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @group.update(group_params)
      redirect_to groups_path
    else
      render "edit"
    end
  end
  
  private
    
    def group_params
      params.require(:group).permit(:name, :introduction)
    end
    
    # def ensure_correct_user
    #   @group = Group.find(params[:id])
    #   unless @group.owner_id == current_user.id
    #     redirect_to groups_path
    #   end
    # end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "ユーザー認証メールを送信いたしました。認証が完了しましたらログインをお願いいたします。"
      redirect_to new_user_session_path
    else
      flash[:alert] = "ユーザー登録に失敗しました。"
      render action: :new and return
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  private

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  end
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/index.html.erb
<section class="groups">
  <h2 class="groups-title">グループ</h2>
</section>

app/views/layouts/_header.html.erb
<header>
  
  <h1 class="app-title">
    <%= link_to "Group continue", '/' %>
  </h1>
  
  <nav id="navi">
    <ul>
      <li><%= link_to "アカウント作成", new_user_registration_path, class: "header-signup" %></li>
      <li><%= link_to "ログイン", new_user_session_path, class: "header-login" %></li>
    </ul>
  </nav>
  
</header>

app/views/layouts/_header_login.html.erb
<header>
  
  <h1 class="app-title">
    <%= link_to "Group continue", root_url %>
  </h1>
  
  <nav id="navi">
    <ul>
      <li><%= link_to "グループ一覧", root_url, class: "header-group-nav" %></li>
      <li><%= link_to "グループを作成する", new_group_path, class: "header-group-nav" %></li>
      <li><%= link_to "グループに参加する", destroy_user_session_path, class: "header-group-nav" %></li>
      <li class="header-logout-li"><%= link_to "ログアウト", destroy_user_session_path, class: "header-logout", method: :delete %></li>
    </ul>
  </nav>
  
</header>

app/views/layouts/_header_not_login.html.erb
<header>
  
  <h1 class="app-title">
    <%= link_to "Group continue", '/' %>
  </h1>
  
  <nav id="navi">
    <ul>
      <li class="header-signup-li"><%= link_to "アカウント作成", new_user_registration_path, class: "header-signup" %></li>
      <li class="header-login-li"><%= link_to "ログイン", new_user_session_path, class: "header-login" %></li>
    </ul>
  </nav>
  
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Groupcontinue</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <% if user_signed_in? %>
    <%= render 'layouts/header_login' %>
  <% else %>
    <%= render 'layouts/header_not_login' %>
  <% end %>
  <main>
    <div class="background"></div>
    <div class="container">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </main>
</body>
</html>

app/views/static_pages/index.html.erb
<div class="index-text">
  <h2>テキストテキストテキストテキストテキストテキストテキストテキストテキストテキスト</h2>
</div>
<section class="index-form">
  <div class="index-form-app-title-area">
    <h1 class="index-form-app-title">
      <%= link_to "Group continue", '/' %>
    </h1>
  </div>
  <div class="index-form-action">
    <ul>
      <li><%= link_to "アカウント作成", new_user_registration_path, class: "index-signup" %></li>
      <li><%= link_to "ログイン", new_user_session_path, class: "index-login" %></li>
    </ul>
  </div>
</section>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>